name: deploy vue 

on:
  push:
    branches:
      - master

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4 

      - name: setup pnpm
        uses: pnpm/action-setup@v4 
        with:
          run_install: false

      - name: Use Node.js 20.x
        with:
          node-version: 20
          cache: 'pnpm'

      - name: build the code
        run: | # คำสั่งติดตั้ง library และ build โปรเจกต์
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: copy file to server
        uses: appleboy/scp-action@master # ส่งไฟล์ที่ build เสร็จแล้วไปที่ EC2
        with:
          host: ${{secrets.HOST}} # เลข IP ของเครื่อง VM ใหม่
          username: ${{secrets.SSH_USER_NAME}} # ปกติคือ ubuntu
          key: ${{secrets.SSH_KEY}} # Private Key ที่คู่กับเครื่อง VM ใหม่
          source: "./dist/*" # โฟลเดอร์ที่ได้จากการ build
          target: "/var/www/html"
          strip_components: 1